[global]
repo1-path=/var/lib/pgbackrest
repo1-retention-full=2
start-fast=y
log-level-console=info
archive-async=y
spool-path=/var/spool/pgbackrest

repo2-type=s3
repo2-path=/repo
repo2-s3-bucket=pgbackrest
repo2-s3-endpoint=minio
repo2-storage-port=9000
repo2-s3-region=us-east-1
repo2-s3-uri-style=path
repo2-storage-ca-file=/etc/pgbackrest/ca.crt
repo2-cipher-type=aes-256-cbc
repo2-retention-full=2

repo3-type=s3
repo3-path=/repo
repo3-s3-bucket=pgbackrest-locked
repo3-s3-endpoint=minio
repo3-storage-port=9000
repo3-s3-region=us-east-1
repo3-s3-uri-style=path
repo3-storage-ca-file=/etc/pgbackrest/ca.crt
repo3-cipher-type=aes-256-cbc
repo3-retention-full=2

[global:archive-push]
process-max=4

[global:archive-get]
process-max=4

[main]
pg1-path=/var/lib/postgresql/data